### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by maschuep** [m-cirkovic/Open-Data_ASTRA#1]
- [ ] Errors darstellen
    - [ ] mapping
    - [ ] weil die errormessage sowieso immer im typ ist kann man sie beim mappen auch gleich auslesen
    - [ ] erkennen und integrieren
- [ ] Messung mit Farzeugart mappen
- [ ] D3 integration
- [ ] schön darstellen
- [ ] filteroptionen
    - [ ] errors ausblenden
    - [ ] regional
    - [ ] favourites?
    - [ ] nur prekäre
    - [ ]

**Comment by maschuep** [comment]
EMPTY_RESPONSE: Der Datenlieferant ist offline.
PRV_OFFLINE:	Ein Drittanbieter-System ist momentan offline.
AGG_OFFLINE:	Der Aggregationsdienst ist momentan offline.
VD_OFFLINE: Die Kommunikation zum Verkehrszähler ist unterbrochen oder der Verkehrszähler ist offline. Es werden im Moment keine Daten empfangen.
VD_ERROR: Der Verkehrszähler ist defekt und sendet daher keine oder ungültige Daten.
SENSOR_ERROR: Der Sensor des Verkehrszählers ist offline oder defekt und sendet daher keine oder ungültige Daten.
SENSOR_WWD: Der Sensor hat Verkehr in Gegenrichtung detektiert. Mögliche Ursachen: Umleitung wegen Baustelle, Falschfahrer oder zum Beispiel durch ein Überholmanöver.
